[project]
name = "shopware-plugin-builder"
version = "0.1.0"
description = "Build and package Shopware 6 plugins for release"
requires-python = ">=3.8"
dependencies = [
    "rich>=13.0.0",
    "click>=8.0.0",
    "pytz",
]

[project.scripts]
sw-build = "shopware_plugin_builder.cli:main"

